extends Node

enum CardType { COLOR, JOKER, CHARACTER, BACK }
enum CardColor { PINK, RED, ORANGE, YELLOW, GREEN, BLUE, VIOLET }
enum CardCharacter { NONE, MATH_TEACHER, SPORTSY, PROM_QUEEN, NOSEY, HISTORY_TEACHER, 
	THEATER_KID, CLASS_PRESIDENT, ART_TEACHER, BAD_BOY }
